#! /usr/share/php/drush/drush.php

drush_print("HELLO\n\n");


//$query = new \EntityQuery();
//$query->entityCondition( 'entity_type', 'redhen_contact' );
//$result = $query->execute();
$result = entity_get_info('redhen_contact');
$fh = fopen('/home/phylogram/redhen_contact.json', 'w');
fwrite($fh, json_encode($result));
fclose($fh);
/**
$loaded = array();

foreach (array_keys($result['redhen_contact']) as $id) {
$loaded[$id] = entity_load('redhen_contact', $id);
}


$fh = fopen('/home/phylogram/redhen_contact_loaded.json', 'w');
fwrite($fh, json_encode($loaded));
fclose($fh);
*/